name: cs3_portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  font_awesome_flutter: ^10.7.0
  infinite_carousel: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: WindSong
      fonts:
        - asset: assets/fonts/WindSong-Regular.ttf
        - asset: assets/fonts/WindSong-Medium.ttf
